name: mybookapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase: ^7.3.3
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_database: ^4.4.0
  splash_screen_view: ^1.0.1
  flutter_login: ^1.0.14
  toast: ^0.1.5
  flutter_staggered_animations: "^0.1.2"


  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"

flutter_icons:
  image_path: "images/books.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/